name: jeepneygo_milestone
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/JeepneyGo.png
    - assets/images/angeles_city_jeepney.png
    - assets/images/jeepney_route1.png
    - assets/images/jeepney_route2.png
    - assets/images/jeepney_route3.png
